services:
  - type: web
    name: notes-api
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

databases:
  - name: notes-db
    databaseName: railway
    user: postgres
    plan: free
